# Generated by Django 5.0.6 on 2024-09-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
